replicaCount: 1

image:
  repository: grafana/loki
  tag: 2.9.0
  pullPolicy: IfNotPresent

storage:
  size: 5Gi
  className: standard  # This is directly set without Go templating

service:
  type: ClusterIP
  port: 3100

resources: {}

# PVC configuration to create the PersistentVolumeClaim
persistence:
  enabled: true
  storageClassName: standard  # Directly set to 'standard'
  accessModes:
    - ReadWriteOnce
  size: 5Gi  # Directly set the storage size
  existingClaim: loki-pvc  # Add this to reference your existing PVC

serviceMonitor:
  enabled: false

loki:
  # Expose Loki as a service on port 3100 (default)
  url: http://loki:3100/loki/api/v1/push

# Add any additional custom values for your use case, such as node selectors, tolerations, etc.
nodeSelector: {}
tolerations: []
podAffinity: {}

# Set resources for Loki if needed
resources: {}

# Optional: set the retention policy for logs in Loki (if you want to configure retention)
retention:
  enabled: true
  period: "7d"  # Logs retention period, e.g., 7 days

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
  datasources:
    influxdb:
      name: InfluxDB
      type: influxdb
      url: http://3.85.34.66:8086  # Replace with your InfluxDB instance URL
      access: proxy
      jsonData:
        httpMethod: POST
        timeInterval: "10s"
