apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    auth_enabled: {{ .Values.loki.auth_enabled }}

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      storage:
        {{- toYaml .Values.loki.commonConfig | nindent 8 }}
      path_prefix: /loki
      ring:
        kvstore:
          store: memberlist
        replication_factor: {{ .Values.loki.commonConfig.replication_factor }}

    schema_config:
      configs:
        {{- toYaml .Values.loki.schemaConfig.configs | nindent 8 }}

    storage_config:
      filesystem:
        chunks_directory: {{ .Values.loki.storage.filesystem.chunks_directory }}
        rules_directory: {{ .Values.loki.storage.filesystem.rules_directory }}
      boltdb_shipper:
        {{- toYaml .Values.loki.storage_config.boltdb_shipper | nindent 8 }}

    ingester:
      {{- toYaml .Values.loki.ingester | nindent 6 }}

    limits_config:
      {{- toYaml .Values.loki.limits_config | nindent 6 }}

    compactor:
      {{- toYaml .Values.loki.compactor | nindent 6 }}

    memberlist:
      {{- toYaml .Values.loki.memberlist | nindent 6 }}

    query_scheduler:
      {{- toYaml .Values.loki.query_scheduler | nindent 6 }}
