apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-loki-config
  namespace: loki
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: debug

    storage_config:
      boltdb_shipper:
        active_index_directory: /mnt/data/loki/index
        cache_location: /mnt/data/loki/cache
      filesystem:
        directory: /mnt/data/loki/chunks

    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

    index:
      prefix: loki_index_
      period: 24h

    limits_config:
      enforce_metric_name: false
      ingestion_rate_mb: 5
      ingestion_rate_limit: 5000000
      max_entries_limit: 50000

    scrape_configs:
      - job_name: 'loki'
        static_configs:
          - targets: ['localhost:3100']
