apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    app: {{ include "loki.name" . }}
    chart: {{ include "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "loki.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "loki.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      initContainers:
        - name: fix-permissions
          image: alpine:3.18
          command: ["sh", "-c", "chown -R 10001:10001 /loki"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: storage
              mountPath: /loki
      containers:
        - name: loki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /mnt/data/loki 
      volumes:
        - name: config
          configMap:
            name: {{ include "loki.fullname" . }}-config
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "loki.fullname" .) }}
