apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    chart: loki-chart
    release: my-release
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      release: my-release
  template:
    metadata:
      labels:
        app: loki
        release: my-release
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      initContainers:
        - name: fix-permissions
          image: alpine:3.18
          command: ["sh", "-c", "chown -R 10001:10001 /loki"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: storage
              mountPath: /loki
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /mnt/data/loki
      volumes:
        - name: config
          configMap:
            name: loki-loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-pvc
