apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "loki.fullname" . }}-pv
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "50Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
  hostPath:
    path: /data/loki
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node1 # Specify your node hostname
