apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki.fullname" . }}-pvc
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "50Gi" }}
  selector:
    matchLabels:
      {{- include "loki.labels" . | nindent 6 }}
