apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki.fullname" . }}-pvc
  namespace: {{ .Release.Namespace | default "loki" }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
  accessModes:
    - {{ .Values.persistence.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "50Gi" }}
  {{- if .Values.persistence.selector }}
  selector:
    {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- else }}
  selector:
    matchLabels:
      app: {{ include "loki.name" . }}
      release: {{ .Release.Name }}
  {{- end }}
