{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  endpoints:
    - port: http
      interval: 15s
{{- end }}
